version: '3'

services:
  php:
    image: phpsymfony
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:8000
    command: "/root/.symfony5/bin/symfony server:start"
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_ROOT_USER=${DB_ROOT_USERNAME}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80