version: '3'

services:
  php:
    image: phpsymfony
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:8000
    command: "/root/.symfony5/bin/symfony server:start"
    restart: always
    container_name: symfonywebapp
  db:
    image: mysql:5.7.16
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_ROOT_USER=${DB_ROOT_USERNAME}
    volumes:
      - ./dbData:/var/lib/mysql
      - ./RepositoryInit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    restart: always
    container_name: mysqldb
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always
    container_name: phpmyadmin
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###