<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGVjzix\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGVjzix/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGVjzix.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGVjzix\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZGVjzix\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZGVjzix',
    'container.build_id' => '1db64234',
    'container.build_time' => 1721664368,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGVjzix');
