<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSaA2rr2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSaA2rr2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSaA2rr2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSaA2rr2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSaA2rr2\App_KernelDevDebugContainer([
    'container.build_hash' => 'SaA2rr2',
    'container.build_id' => '3ca3aa2a',
    'container.build_time' => 1721315629,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSaA2rr2');
